### ISSUE TITLE
Prompt or something issue

### ISSUE THREAD

**Issue by etozherstk** [vfnm/Poe-API-Server#10]
![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/b2f97ae9-b522-40bc-82e3-a4b3cdbf3b0f)

Anyway thank to stuff i can get at least one single message

**Comment by vfnm** [comment]
Update to newest version and follow this: For GPT-3.5/4 based bots you can get better results by changing the value of 'instruction' in config.json to 'Read the instructions in here' or similar

**Comment by etozherstk** [comment]
> 

![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/ce680b2b-27a0-4323-b026-9b1d2b4be4cc)
wait, config.json? maybe im a bit of stupid but i really dont get it

**Comment by vfnm** [comment]
It will be created after you use the program for the first time.

**Comment by etozherstk** [comment]
> Read the instructions in here

![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/a03c1608-8cb9-40c0-acf8-43401d548141)
Is it okay theres nothing wroten?

**Comment by vfnm** [comment]
It should look like this
`"instruction": "Read the instructions in here"`

**Comment by newel123** [comment]
Even with the instructions placed in the config.json the bot doesn't seem to work.

**Comment by etozherstk** [comment]
> Even with the instructions placed in the config.json the bot doesn't seem to work.

same thing

**Comment by vfnm** [comment]
To troubleshoot, add your console output and a screenshot of the Poe.com chat history with the bot that is being used.

**Comment by JAndrean29** [comment]
here's from what I can understand from my usage of he new version

the problems is that when user sends the request it doesn't send the instruction included in the config.json (at least it doesn't show on POE, but it does work on my next explanation) and when a request is sent a new config.json is remade overwriting the one with the added instruction

you can try to make the config.json file into a read-only file if you plan to keep using one kind of bot, but it is still not 100% working as it will either:

1. response with the same prompt problem and response won't finish (button doesn't return to send button but still stuck on stop button despite in poe it is finished) (it seems renewing he config.json file was a necessary process to complete the request)
2. the bot gives out a proper chat reply but its the same as no.1 as the response won't finish

The results were inconsistent but it mostly lean still into the prompt problem even making the config.json a read only file, I hope this will give some clarity on the issue at hand at least this is what I find and understands so far

**Comment by etozherstk** [comment]
> here's from what I can understand from my usage of the new version
> 
> the problems is that when user sends the request it doesn't send the instruction included in the config.json (at least it doesn't show on POE, but it does work actually) and when a request is sent a new config.json is remade overwriting the one with the added instruction
> 
> you can try to make the config.json file into a read-only file if you plan to keep using one kind of bot, but it is still not 100% working as it will either:
> 
> 1. response with the same prompt problem and response won't finish (button doesn't return to send button but still stuck on stop button despite in poe it is finished) (it seems renewing he config.json file was a necessary process to complete the request)
> 2. sometimes the bot will gives out a proper chat reply but its the same as no.1 as the response won't finish
> 
> The results were inconsistent but it mostly lean still into the prompt problem even making the config.json a read only file, I hope this will give some clarity on the issue at hand at least this is what I find and understands so far

i tested it right now, it still sucks 
![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/23b69df6-e7fb-450b-870f-4aed656fd268)

**Comment by vfnm** [comment]
@JAndrean29 
Can you show the content of your config.json (minus the cookie)? I just tried it again and it does not overwrite something for me, when I modify the instruction value and restart the program or make another request.
@etozherstk
What bot do you use? It works for me when I try it with a custom ChatGPT or GPT-4 bot and a role play prompt.

**Comment by etozherstk** [comment]
@vfnm 
chatGPT. instead of "Assistant" i write there "chatGPT" (p-b token|chatGPT). 
can you gimme a roleplay prompt? and say please where should i insert?

**Comment by JAndrean29** [comment]
@vfnm sorry it's a false alarm, it seems I didn't a bit rashly and checked it when I still running it for the first time making it recreating the config.json, think I still opened it the first time (idk if that is truly the case) but it's all fine

though the issue now is that ChatGPT (the normal one not any custom bot based on it) becomes less easy to jb for some reason giving me these results

Failed to consent:
![image](https://github.com/vfnm/Poe-API-Server/assets/120368066/07402376-7737-41bd-889a-a49a583a4a8e)

Success but this one is a bit weird, since in the ST client the message stops on the first paragraph and requires me to regenerate the response to get the full response
![image](https://github.com/vfnm/Poe-API-Server/assets/120368066/3a3a27bf-d0f5-449b-9d06-8ceb56e6e501)

On the ST side I got the full response from the previous image but in poe the bot regenerates a new response still
![image](https://github.com/vfnm/Poe-API-Server/assets/120368066/36421bdb-8518-47c6-b8f0-50923a61e18b)

I guess from my side I'll just change back to a custom gpt bot

**Comment by JAndrean29** [comment]
@vfnm another issue would be that ST can't sync with the proper response did you experience this yourself? or maybe you can show me your settings? I am using GPTforST custom bot rn

**Comment by vfnm** [comment]
Fixed in latest commit (look at step 10 in the guide).
