### ISSUE TITLE
Option to change between prompt text and txt file

### ISSUE THREAD

**Issue by tomiiiiiiiii** [vfnm/Poe-API-Server#13]
It would be good to have an option in the config file to change between prompt text and txt file. Txt file works perfectly with Claude-Instant but the bot has a lot of problems with formatting.

In Sage, it really doesn't work well, even with the "Read the instructions in this file" thing, sometimes it doesn't read the context or the jailbreak, back in the 0.1 version, when the prompt text was sent (instead of the txt file) it worked pretty fine.

**Comment by vfnm** [comment]
Do you still have a problem when using ChatGPT or a custom bot with a role play prompt instead?

**Comment by Exinetii** [comment]
We all do

**Comment by vfnm** [comment]
Fixed in latest commit (look at step 10 in the guide).
