### ISSUE TITLE
Connection issues in sillytavern

### ISSUE THREAD

**Issue by KakDealz** [vfnm/Poe-API-Server#15]
When I try to connect I get the "GET /v2/driver/sage/models HTTP/1.1" 500 - error. Even though I separated p-b key and bot's name with |
![image](https://github.com/vfnm/Poe-API-Server/assets/92873721/bcaecd79-0acd-4e22-98a0-8c0a68adf555)

**Comment by vfnm** [comment]
Try to do it with this | (copy and paste it).

**Comment by KakDealz** [comment]
I did separate the p-b key and bot's name like "key|Claude-2-100k". I tried connecting now and it just magically fixed itself, idk what I did to fix it, but now it's working at least.
