### ISSUE TITLE
GPT Chat It doesn't work, it says this and I already have version 0.3

### ISSUE THREAD

**Issue by lanmaster2407** [vfnm/Poe-API-Server#16]
Good morning, today I downloaded version 0.3 and my problem has not yet been resolved. I have not been able to speak at all, I have been patient but even this does not work for me, here I leave the images that say more than enough
![Screenshot_49](https://github.com/vfnm/Poe-API-Server/assets/138830028/42988cfd-fc37-44de-a3b6-40f7368ec1d0)
It doesn't do anything and Silly tarven always says the same thing I'm upset... I want my characters back :C

**Comment by vfnm** [comment]
Follow Step 9.

**Comment by lanmaster2407** [comment]
Friend, I've tried everything but it still doesn't work....could you give me the config? I already tried it but the bot refuses to cooperate. Here I leave you screenshots so you can see if I put something wrong.
![Captura de Falla GP34](https://github.com/vfnm/Poe-API-Server/assets/138830028/b486e9fd-d2a7-44fe-ac93-db53b5027bd2)
