### ISSUE TITLE
Hopeless

### ISSUE THREAD

**Issue by darkwarriorx0545** [vfnm/Poe-API-Server#17]
It's absolutely horrible, after only few messages character starts writing as user and no one else, even if i clearly said in main prompt not to do so. Also, no matter how many times i mention the reply length limit, bot doesn't care and writes literal books instead of one quick response. Not to mention it's horribly slow and overall makes chatting with characters not fun, but frustrating! The bot often repeats the whole messages. I have the latest version (0.3), setting context size to 2048 or higher does nothing, im hopeless.

**Comment by vfnm** [comment]
I can't really do something about many of those issues as they are related to the LLM or Poe. The issue with the bot repeating the last message will be fixed in the next version.
