### ISSUE TITLE
I'm sorry, I'm not sure what you're trying to ask or if there's a specific question you have. Could you please provide more context or clarify your request?

### ISSUE THREAD

**Issue by Exinetii** [vfnm/Poe-API-Server#19]
"I'm sorry, I'm not sure what you're trying to ask or if there's a specific question you have. Could you please provide more context or clarify your request?" I went to config.json and changed "-" to "Read the instruction here" or "Read the instructions in this file" Same thing happes, When i use Version 0.1 it works fine. can you revert this update? or maybe just add an option to use text instead of txt files?

**Comment by darkwarriorx0545** [comment]
same problem 🥲

**Comment by tyranzero** [comment]
even adding prompt for example "Write {{char}}'s next reply" into the main prompt or config solve nothing?

**Comment by vfnm** [comment]
Fixed in latest commit (look at step 10 in the guide).
