### ISSUE TITLE
[Thank You and Question]

### ISSUE THREAD

**Issue by LegionInstaller** [vfnm/Poe-API-Server#2]
First Of all Thank You so much for Implementing POE back to ST

Is Authors Note Implemented ?

**Comment by VaniusK** [comment]
It basically collect all messages st normally sends and sends them all in once. St sends authors note so yes, it should be implemented

**Comment by LegionInstaller** [comment]
> It basically collect all messages st normally sends and sends them all in once. St sends authors note so yes, it should be implemented

Very Nice
