### ISSUE TITLE
"Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)

### ISSUE THREAD

**Issue by Rikoz2528** [vfnm/Poe-API-Server#23]
It keeps spamming this error and now i can't chat.

**Comment by coffeebrown0** [comment]
Same issue.

**Comment by vfnm** [comment]
Fixed in latest commit, but had to disable headless mode.

**Comment by coffeebrown0** [comment]
Thank you for all your work bfnm, really appreciate you!
