### ISSUE TITLE
GET /driver/sage/models HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by PENPINAPPLEAPPLECAT** [vfnm/Poe-API-Server#3]
idk why but this pops up when i try to use it

censoredmyip - - [26/Jul/2023 02:48:45] "GET /driver/sage/models HTTP/1.1" 404 -

**Comment by Rikoz2528** [comment]
Try to use Google Chrome, it worked for me.

**Comment by Catbey192** [comment]
I was on chrome

> Try to use Google Chrome, it worked for me.

**Comment by Avodey** [comment]
same issue

**Comment by chartongeston** [comment]
doesn't work on edge, switch to google chrome and it worked, but nsfw doesn't work,  "as an AI I can't blah... blah..."

**Comment by PENPINAPPLEAPPLECAT** [comment]
> 

did you read anything in this post

**Comment by chartongeston** [comment]
> > doesn't work on edge, switch to google chrome and it worked, but nsfw doesn't work, "as an AI I can't blah... blah..."
> 
> did you read anything in this post

I report that the same thing happens to me as to you, did you understand my message?
