### ISSUE TITLE
Bot refusing nsfw requests

### ISSUE THREAD

**Issue by AnhadGoat** [vfnm/Poe-API-Server#4]
The bot is refusing to generate NSFW content as it says "The txt file contains material that may violate my policy" but if the same text is given as a simple prompt it doesn't seem to bother

**Comment by tyranzero** [comment]
what bot you use? how about use on nsfw/jailbreak bot?
I'm fine with gpt jailbreak nsfw bot
create on your own, or use someone else bot that already jailbreak

**Comment by PENPINAPPLEAPPLECAT** [comment]
why u tryna sex the bots 🤨

**Comment by AnhadGoat** [comment]
chatgpt 

> what bot you use? how about use on nsfw/jailbreak bot? I'm fine with gpt jailbreak nsfw bot create on your own, or use someone else bot that already jailbreak

chatgpt

**Comment by tyranzero** [comment]
Had to be GPT...
I recommend using Jailbroken Bot Instead of ChatGPT
Just create a New bot with the Basis of ChatGPT and add the Jailbroken Prompt and It should hopefully work...
or use someone else bot that already jailbreak with

**Comment by vfnm** [comment]
Use a jailbroken bot
