### ISSUE TITLE
"API returned an error"

### ISSUE THREAD

**Issue by etozherstk** [vfnm/Poe-API-Server#5]
![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/f7143399-4373-4447-b3bd-1f115056160e)
![image](https://github.com/vfnm/Poe-API-Server/assets/139702880/7c52b36c-523e-42da-80f8-b0c564d7cc3b)

**Comment by vxxlfs** [comment]
same issue

**Comment by vfnm** [comment]
Restart it when this occurs. In the next release I will try to implement some mechanism to automatically resolve this issue.

**Comment by vfnm** [comment]
Fixed in new commit
