### ISSUE TITLE
The bot does not answer the questions or Role Play any solution?

### ISSUE THREAD

**Issue by lanmaster2407** [vfnm/Poe-API-Server#7]
I need help with this... since I want to try it but when I go to try any dialog the bot responds with this, here I leave the images for a better context.
![image](https://github.com/vfnm/Poe-API-Server/assets/138830028/9c53963d-11ee-4025-9b7e-02ea5c84683c)
![Screenshot_49](https://github.com/vfnm/Poe-API-Server/assets/138830028/bb3c1b2d-e04a-49e1-810d-b81598a2132e)

**Comment by vfnm** [comment]
Fixed in new commit
