### ISSUE TITLE
POST requests to /v2/driver/sage/chat/completions send .txt file instead of prompt

### ISSUE THREAD

**Issue by chikibreki** [vfnm/Poe-API-Server#9]
Version: Windows Release 0.2
Model: ChatGPT

Poe screenshot

![image](https://github.com/vfnm/Poe-API-Server/assets/7354770/bbc872fc-7376-48a1-9cbb-05f728a6233c)

Applications terminal output: [application_output.txt](https://github.com/vfnm/Poe-API-Server/files/12178689/application_output.txt)

SillyTavern terminal output: [sillytavern_terminal_output.txt](https://github.com/vfnm/Poe-API-Server/files/12178691/sillytavern_terminal_output.txt)

Text file sent to Poe: [3776d89be45854770c31ff86e46715d2ef1484c6ba38da14e3f7695aad0de3b8.txt](https://github.com/vfnm/Poe-API-Server/files/12178696/3776d89be45854770c31ff86e46715d2ef1484c6ba38da14e3f7695aad0de3b8.txt)

**Comment by LegionInstaller** [comment]
Mine also sends a TXT but works fine, I recommend using a Jailbroken Bot Instead of ChatGPT
Just create a New bot with the Basis of ChatGPT and add the Jailbroken Prompt and It should hopefully work

**Comment by vfnm** [comment]
Fixed in new commit

**Comment by vfnm** [comment]
Fixed in new commit
